# Generated by Django 4.2.8 on 2024-10-08 07:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_status_alter_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['time_created'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768, verbose_name='Векторное представление текста'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='documents.status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='documents.type'),
        ),
    ]
