# Generated by Django 4.2.8 on 2024-10-08 08:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_options_document_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='documents.status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='documents.type'),
        ),
    ]
