# Generated by Django 4.2.8 on 2024-10-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_last_status_changed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(verbose_name='Схожесть')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_documents', to='documents.document')),
                ('similar_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_similar_to', to='documents.document')),
            ],
            options={
                'verbose_name': 'Похожий документ',
                'verbose_name_plural': 'Похожие документы',
                'db_table': 'similar_document',
            },
        ),
    ]
