# Generated by Django 4.2.8 on 2024-10-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_similardocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similardocument',
            name='similar_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='documents.document'),
        ),
    ]
