# Generated by Django 4.2.9 on 2025-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_similardocument_similar_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='vector',
            field=models.TextField(blank=True, null=True, verbose_name='Векторное представление текста'),
        ),
    ]
