# Generated by Django 4.2.9 on 2025-10-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_update_types"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="-- No-op: extension removal is unsafe in shared DBs",
        ),
    ]


